name: Placeholder

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  placeholder:
    runs-on: ubuntu-latest

    steps:
      - name: Echo
        run: echo "I'm a teapot!"
